CREATE TABLE `competitor_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`competitorName` varchar(255) NOT NULL,
	`website` varchar(500),
	`positioning` text,
	`strengths` text,
	`weaknesses` text,
	`priceInfo` text,
	`contentAssets` text,
	`aiRecommendationSignals` text,
	`comparisonNotes` text,
	`sourceAssetIds` json NOT NULL,
	`canReference` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitor_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `compliance_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`ruleName` varchar(255) NOT NULL,
	`forbiddenClaims` text,
	`forbiddenWords` json NOT NULL,
	`requiredDisclaimers` text,
	`dataUsageRules` text,
	`caseUsageRules` text,
	`priceUsageRules` text,
	`competitorMentionRules` text,
	`reviewRequiredTopics` json NOT NULL,
	`enabled` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `compliance_rules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `content_style_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`profileName` varchar(255) NOT NULL,
	`tone` varchar(255) NOT NULL,
	`writingStyle` text,
	`terminology` json NOT NULL,
	`forbiddenTone` text,
	`exampleTitles` json NOT NULL,
	`exampleParagraphs` json NOT NULL,
	`targetReader` text,
	`preferredLength` varchar(255),
	`ctaStyle` text,
	`enabled` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_style_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customer_cases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`caseType` enum('真实案例','待补充案例线索') NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerIndustry` varchar(255),
	`customerBackground` text,
	`originalProblem` text,
	`chosenReason` text,
	`usedProductService` text,
	`executionProcess` text,
	`resultData` text,
	`customerFeedback` text,
	`allowPublic` int NOT NULL DEFAULT 0,
	`publicVersion` text,
	`sensitiveNotes` text,
	`sourceAssetIds` json NOT NULL,
	`verificationStatus` enum('待确认','已确认','不可公开','信息不足') NOT NULL DEFAULT '待确认',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customer_cases_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `enterprise_geo_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`enterpriseName` varchar(255) NOT NULL,
	`shortName` varchar(255),
	`officialWebsite` varchar(500),
	`industry` varchar(255),
	`region` varchar(255),
	`productServiceIntro` text,
	`targetCustomers` text,
	`coreSellingPoints` text,
	`servicePriceRange` varchar(255),
	`serviceModel` text,
	`fitCustomers` text,
	`unfitCustomers` text,
	`salesChannels` json NOT NULL,
	`commonQuestions` json NOT NULL,
	`purchaseDecisionFactors` json NOT NULL,
	`productIntro` text,
	`featureNotes` text,
	`serviceProcess` text,
	`deliveryPlan` text,
	`afterSalesService` text,
	`competitorDifference` text,
	`priceExplanation` text,
	`salesTalkTracks` text,
	`commonObjections` text,
	`completionScore` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `enterprise_geo_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `geo_asset_sources` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`sourceType` enum('企业基础资料','产品服务资料','客户案例资料','竞品资料','合规资料','内容风格资料','发布策略资料','通用资料') NOT NULL,
	`inputMode` enum('文件上传','文本粘贴','人工录入') NOT NULL,
	`title` varchar(255) NOT NULL,
	`originalFileName` varchar(500),
	`fileKey` varchar(1000),
	`fileUrl` varchar(1000),
	`mimeType` varchar(255),
	`contentDigest` text,
	`structuredSummary` json NOT NULL,
	`trustLevel` enum('高','中','低') NOT NULL DEFAULT '中',
	`parseStatus` enum('待解析','已解析','解析失败','人工确认') NOT NULL DEFAULT '待解析',
	`isPublic` int NOT NULL DEFAULT 0,
	`canUseForGeneration` int NOT NULL DEFAULT 0,
	`manuallyConfirmed` int NOT NULL DEFAULT 0,
	`parsedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `geo_asset_sources_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `platform_authorization_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`platformName` varchar(255) NOT NULL,
	`accountAlias` varchar(255),
	`authorizationStatus` enum('未配置','待人工授权','已授权','已失效','无需授权') NOT NULL DEFAULT '未配置',
	`credentialStorageMode` varchar(255) NOT NULL DEFAULT '不保存明文凭证',
	`secureCredentialRef` varchar(500),
	`authorizationNotes` text,
	`authorizedAt` timestamp,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `platform_authorization_configs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `publish_strategies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`strategyName` varchar(255) NOT NULL,
	`reviewMode` enum('全人工审核','高分自动发布','全自动发布') NOT NULL DEFAULT '全人工审核',
	`dailyLimit` int,
	`minQualityScore` int NOT NULL DEFAULT 80,
	`preferredPlatforms` json NOT NULL,
	`bannedPlatforms` json NOT NULL,
	`platformNotes` text,
	`enabled` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `publish_strategies_id` PRIMARY KEY(`id`)
);
