import "dotenv/config";
import {randomUUID} from "node:crypto";
import {and,eq} from "drizzle-orm";
import {brandTruthEvidence,brandTruthFactEvidenceLinks,brandTruthFacts,trustEvidenceFactLinks,trustEvidenceLedgerItems,trustEvidenceQuestionLinks,trustEvidenceSources,trustSourceSnapshots,understandingAssessments,understandingMethodologyDimensionDefinitions,understandingQuestionDimensionBindings,understandingQuestionVersions,understandingRolloutConfigs} from "../drizzle/schema";
import {getDb} from "../server/db";
import {EVIDENCE_TYPES,EvidenceLedgerService} from "../server/evidenceLedgerService";
const projectId=210001;
if(process.env.CONFIRM_210001_EVIDENCE_LEDGER!=="true")throw new Error("explicit evidence ledger confirmation required");
if(process.env.AI_OBSERVATION_LEDGER_V2?.toLowerCase()==="true")throw new Error("global v2 flag must remain false");
const db=await getDb();if(!db)throw new Error("DATABASE_URL required");
const svc=new EvidenceLedgerService(db);
const classify=(row:any):(typeof EVIDENCE_TYPES)[number]=>{const v=`${row.evidenceType} ${row.title}`.toLowerCase();if(v.includes("faq"))return"faq";if(v.includes("schema"))return v.includes("product")?"product_schema":v.includes("organization")?"organization_schema":"brand_schema";if(v.includes("产品"))return"product_page";if(v.includes("媒体"))return"media";if(v.includes("案例"))return"customer_case";if(v.includes("合作"))return"partner";if(v.includes("github"))return"github";if(v.includes("知乎"))return"zhihu";if(v.includes("公众号"))return"wechat_official_account";if(v.includes("视频"))return"video";if(v.includes("company")||v.includes("公司"))return"company";return row.sourceClass==="official"?"official_homepage":"industry_platform";};
const baselineBefore={assessments:(await db.select().from(understandingAssessments).where(eq(understandingAssessments.projectId,projectId))).length};
const rollout=(await db.select().from(understandingRolloutConfigs).where(eq(understandingRolloutConfigs.projectId,projectId)).limit(1))[0];if(rollout?.readMode!=="shadow_read"||rollout.writePath!=="legacy")throw new Error("210001 rollout boundary changed");
const [legacyEvidence,legacyLinks,facts,questions,bindings,definitions]=await Promise.all([db.select().from(brandTruthEvidence).where(eq(brandTruthEvidence.projectId,projectId)),db.select().from(brandTruthFactEvidenceLinks).where(eq(brandTruthFactEvidenceLinks.projectId,projectId)),db.select().from(brandTruthFacts).where(eq(brandTruthFacts.projectId,projectId)),db.select().from(understandingQuestionVersions).where(eq(understandingQuestionVersions.projectId,projectId)),db.select().from(understandingQuestionDimensionBindings).where(eq(understandingQuestionDimensionBindings.projectId,projectId)),db.select().from(understandingMethodologyDimensionDefinitions).where(eq(understandingMethodologyDimensionDefinitions.projectId,projectId))]);
let imported=0,snapshots=0,factLinkCount=0,questionLinkCount=0;
for(const legacy of legacyEvidence){if(!legacy.url)continue;let source=(await db.select().from(trustEvidenceSources).where(and(eq(trustEvidenceSources.projectId,projectId),eq(trustEvidenceSources.sourceUrl,legacy.url))).limit(1))[0];let item:typeof trustEvidenceLedgerItems.$inferSelect|undefined;
  if(!source){const created=await svc.create({projectId,sourceUrl:legacy.url,sourceOwner:legacy.sourceOwner??legacy.publisher,ownership:legacy.sourceClass==="official"?"owned":"third_party",independentSource:legacy.independentSource,evidenceType:classify(legacy),reviewStatus:legacy.manualReviewStatus==="approved"&&legacy.verificationStatus==="verified"?"approved":"unverified",confidence:null});source=(await db.select().from(trustEvidenceSources).where(eq(trustEvidenceSources.id,created.sourceId)).limit(1))[0];item=(await db.select().from(trustEvidenceLedgerItems).where(eq(trustEvidenceLedgerItems.id,created.itemId)).limit(1))[0];imported++;
    if(legacy.capturedAt||legacy.evidenceHash){const snapshotId=randomUUID(),accessedAt=legacy.capturedAt??legacy.createdAt;await db.insert(trustSourceSnapshots).values({id:snapshotId,projectId,sourceId:source.id,snapshotVersion:1,sourceUrlSnapshot:legacy.url,statusCode:legacy.accessible?200:null,accessedAt,contentHash:legacy.evidenceHash,titleSnapshot:legacy.title,ownerSnapshot:legacy.sourceOwner??legacy.publisher,robotsStatus:"not_checked",publicationTime:legacy.publishedAt,updatedTime:legacy.sourceUpdatedAt,contentExcerpt:legacy.evidenceExcerpt,metadata:{importedFrom:"brand_truth_evidence",legacyEvidenceId:legacy.id}});await db.update(trustEvidenceLedgerItems).set({latestSnapshotId:snapshotId}).where(eq(trustEvidenceLedgerItems.id,item.id));snapshots++;}
  }else item=(await db.select().from(trustEvidenceLedgerItems).where(and(eq(trustEvidenceLedgerItems.projectId,projectId),eq(trustEvidenceLedgerItems.sourceId,source.id))).limit(1))[0];if(!item)continue;
  const linkedFactIds=legacyLinks.filter(x=>x.evidenceId===legacy.id).map(x=>x.factId);for(const factId of linkedFactIds){await svc.linkFact(projectId,item.id,factId,legacyLinks.find(x=>x.evidenceId===legacy.id&&x.factId===factId)?.supportType??"supports");factLinkCount++;const fact=facts.find(x=>x.id===factId);if(!fact)continue;const dims=definitions.filter(d=>(d.factKeys as string[]).includes(fact.factKey)).map(d=>d.dimension);for(const binding of bindings.filter(b=>dims.includes(b.primaryDimension as any)||(b.secondaryDimensions as string[]).some(d=>dims.includes(d as any)))){await svc.linkQuestion(projectId,item.id,binding.questionVersionId,"supporting");questionLinkCount++;}}
  const checked=await svc.checkUrl(projectId,item.id);snapshots++;
}
const gaps=await svc.gaps(projectId),items=await db.select().from(trustEvidenceLedgerItems).where(eq(trustEvidenceLedgerItems.projectId,projectId)),sources=await db.select().from(trustEvidenceSources).where(eq(trustEvidenceSources.projectId,projectId));
const baselineAfter={assessments:(await db.select().from(understandingAssessments).where(eq(understandingAssessments.projectId,projectId))).length};if(JSON.stringify(baselineBefore)!==JSON.stringify(baselineAfter))throw new Error("210001 baseline changed");
console.log(JSON.stringify({status:"passed",projectId,imported,items:items.length,snapshots,factLinks:(await db.select().from(trustEvidenceFactLinks).where(eq(trustEvidenceFactLinks.projectId,projectId))).length,questionLinks:(await db.select().from(trustEvidenceQuestionLinks).where(eq(trustEvidenceQuestionLinks.projectId,projectId))).length,officialEvidence:items.filter(i=>sources.find(s=>s.id===i.sourceId)?.ownership==="owned").length,thirdPartyEvidence:items.filter(i=>sources.find(s=>s.id===i.sourceId)?.ownership==="third_party").length,unverifiedEvidence:items.filter(i=>i.reviewStatus==="unverified").length,evidenceGap:{facts:gaps.length,factsWithoutEvidence:gaps.filter(g=>g.currentEvidence===0).length,missingCategoryCounts:Object.fromEntries(["official","third_party","case","faq","schema","media","partner"].map(category=>[category,gaps.filter(g=>g.missing.includes(category as any)).length]))},baselineUnchanged:true,legacyUnchanged:true,trustGenerated:false}));
